#! /usr/bin/python
import os
import time

warning_message = "/* WARNING: This file has been autogenerated. \
do not modify it directly! */"
template_gen_dir = "templ_gen"

variables = {
    'XM_FUNCTION_PARAM_MAX': 8,
    'XM_GET_N_SET_EXTRA_PARAM_MAX': 3,
    'XM_TEMPLATE_PARAM_MAX' : 4,
    'WARNING_MESSAGE' : warning_message
    }

def gen_seq(string, count, sep = ""):
    res = ""
    if type(count) is tuple:
        start = count[0]
        end = count[1]
    else:
        start = 0
        end = count

    for i in range(start, end):
        if i == start:
            res += string.replace("$", str(i))
        else:
            res += sep + string.replace("$", str(i))
    return res 


def generate_files(variables, dirname, names):
    for filename in names:
        fullname = dirname + "/" + filename
        if os.path.isfile(fullname) and filename.endswith(".py"):
            execfile(fullname, variables)
            fullname = fullname[len(template_gen_dir):]
            if fullname.startswith("/"):
                fullname = fullname[1:]
            fullname = fullname[:-len(".py")]
            f = open(fullname, "w")
            f.write(variables["content"])
            f.close()

variables["gen_seq"] = gen_seq
start_time = time.clock()
os.path.walk(template_gen_dir, generate_files, variables)
print("completed in: " + str(time.clock() - start_time) + "s")